// Shared client for the CEOs program. Used by the setup scripts, the cycle
// job, and the web page.
//
// Instructions are hand-encoded rather than driven off the Anchor IDL: the CLI
// is anchor 1.1.2 but the newest @coral-xyz/anchor on npm is 0.32.1, and a
// silent IDL-format mismatch is a far worse thing to debug than forty lines of
// Buffer writes. Discriminators are sha256("global:<name>")[0..8] and account
// order matches the Accounts structs in anchor/programs/ceos/src exactly.

import { Buffer } from 'buffer';
import { PublicKey, SystemProgram, TransactionInstruction } from '@solana/web3.js';

// From target/deploy/ceos-keypair.json, generated by the first `anchor build`.
// lib.rs is stamped with the same id by `anchor keys sync`; the two must agree.
export const PROGRAM_ID = new PublicKey('3A1sabNyVq3vjnYp3zt6nzr89wNAUJQQBgjwTezr6r7w');
export const MPL_CORE_PROGRAM_ID = new PublicKey('CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d');
export const SLOT_HASHES_SYSVAR = new PublicKey('SysvarS1otHashes111111111111111111111111111');

/// The seven, in class order. Index is the class id everywhere on-chain. `name`
/// is the NFT name prefix the program reads the class back off, so it must
/// match CLASS_NAMES in state.rs character for character.
export const CLASSES = [
  { id: 0, name: 'Jassy',      slug: 'amzn',  ticker: 'AMZN',  stock: 'AMZNx' },
  { id: 1, name: 'Pichai',     slug: 'googl', ticker: 'GOOGL', stock: 'GOOGLx' },
  { id: 2, name: 'Zuckerberg', slug: 'meta',  ticker: 'META',  stock: 'METAx' },
  { id: 3, name: 'Huang',      slug: 'nvda',  ticker: 'NVDA',  stock: 'NVDAx' },
  { id: 4, name: 'Nadella',    slug: 'msft',  ticker: 'MSFT',  stock: 'MSFTx' },
  { id: 5, name: 'Ternus',     slug: 'aapl',  ticker: 'AAPL',  stock: 'AAPLx' },
  { id: 6, name: 'Musk',       slug: 'tsla',  ticker: 'TSLA',  stock: 'TSLAx' },
];
export const CLASS_COUNT = CLASSES.length;

const DISC = {
  initialize:  [175, 175, 109, 31, 13, 152, 155, 237],
  setConfig:   [108, 158, 154, 175, 212, 98, 52, 66],
  mintCeo:     [254, 121, 39, 55, 181, 190, 241, 152],
  initEngine:  [253, 71, 163, 152, 77, 21, 254, 42],
  setEngine:   [66, 87, 78, 112, 218, 132, 52, 45],
  registerCeo: [87, 207, 159, 184, 201, 90, 85, 208],
  runRound:    [82, 55, 203, 200, 140, 117, 4, 81],
  closeCeo:    [215, 64, 221, 143, 53, 49, 17, 165],
  settle:      [175, 42, 185, 87, 144, 131, 102, 212],
};

/// base58 of sha256("account:Ceo")[0..8], for getProgramAccounts filters.
export const CEO_ACCOUNT_FILTER = '5dvDo5n7JBr';

export function configPda() {
  return PublicKey.findProgramAddressSync([Buffer.from('config')], PROGRAM_ID)[0];
}

export function enginePda() {
  return PublicKey.findProgramAddressSync([Buffer.from('engine')], PROGRAM_ID)[0];
}

export function ceoPda(asset) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('ceo'), new PublicKey(asset).toBuffer()],
    PROGRAM_ID,
  )[0];
}

/// Every Core asset has a signer PDA that only its current owner can spend
/// from. That is the NFT's vault — derived, never stored.
export function vaultPda(asset) {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('mpl-core-execute'), new PublicKey(asset).toBuffer()],
    MPL_CORE_PROGRAM_ID,
  )[0];
}

// ---------------------------------------------------------------- encoding

const u8 = (n) => Buffer.from([n & 0xff]);
function u32(n) { const b = Buffer.alloc(4); b.writeUInt32LE(n); return b; }
function u64(n) { const b = Buffer.alloc(8); b.writeBigUInt64LE(BigInt(n)); return b; }
function i64(n) { const b = Buffer.alloc(8); b.writeBigInt64LE(BigInt(n)); return b; }
function borshString(s) {
  const bytes = Buffer.from(s, 'utf8');
  return Buffer.concat([u32(bytes.length), bytes]);
}
/// Borsh `Option<T>`: a 0 byte for None, or a 1 byte followed by the value.
function option(value, encode) {
  return value === null || value === undefined
    ? Buffer.from([0])
    : Buffer.concat([Buffer.from([1]), encode(value)]);
}

function readerFor(data) {
  let o = 8;
  return {
    pubkey: () => { const k = new PublicKey(data.subarray(o, o + 32)); o += 32; return k; },
    u128: () => {
      let v = 0n;
      for (let i = 15; i >= 0; i--) v = (v << 8n) | BigInt(data[o + i]);
      o += 16;
      return v;
    },
    u64: () => { const v = Buffer.from(data.subarray(o, o + 8)).readBigUInt64LE(); o += 8; return v; },
    i64: () => { const v = Buffer.from(data.subarray(o, o + 8)).readBigInt64LE(); o += 8; return v; },
    u32: () => { const v = Buffer.from(data.subarray(o, o + 4)).readUInt32LE(); o += 4; return v; },
    u8: () => data[o++],
    string: () => {
      const len = Buffer.from(data.subarray(o, o + 4)).readUInt32LE(); o += 4;
      const s = Buffer.from(data.subarray(o, o + len)).toString('utf8'); o += len;
      return s;
    },
  };
}
const times = (n, fn) => Array.from({ length: n }, fn);

// ------------------------------------------------------------------ config

export function initializeIx({ authority, collection, treasury, price, supply, uriBase }) {
  if (supply.length !== CLASS_COUNT) throw new Error(`supply must hold ${CLASS_COUNT} entries`);
  const data = Buffer.concat([
    Buffer.from(DISC.initialize),
    new PublicKey(collection).toBuffer(),
    new PublicKey(treasury).toBuffer(),
    u64(price),
    ...supply.map(u32),
    borshString(uriBase),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: true },
      { pubkey: configPda(), isSigner: false, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data,
  });
}

export function setConfigIx({ authority, treasury, price, supply, uriBase }) {
  const data = Buffer.concat([
    Buffer.from(DISC.setConfig),
    option(treasury, (t) => new PublicKey(t).toBuffer()),
    option(price, u64),
    option(supply, (s) => Buffer.concat(s.map(u32))),
    option(uriBase, borshString),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: false },
      { pubkey: configPda(), isSigner: false, isWritable: true },
    ],
    data,
  });
}

/// Layout: 8 disc, 3x pubkey, u64 price, 7x u32 supply, 7x u32 minted,
/// borsh string uri_base, u8 bump.
export function decodeConfig(data) {
  const r = readerFor(data);
  const authority = r.pubkey();
  const collection = r.pubkey();
  const treasury = r.pubkey();
  const price = r.u64();
  const supply = times(CLASS_COUNT, r.u32);
  const minted = times(CLASS_COUNT, r.u32);
  const uriBase = r.string();
  const bump = r.u8();
  return { authority, collection, treasury, price, supply, minted, uriBase, bump };
}

// -------------------------------------------------------------------- mint

/// Two signers: the minter's wallet and the throwaway asset keypair Core needs
/// for a new asset. That is why the page uses signTransaction + partialSign
/// rather than the adapter's sendTransaction — see useChain.js.
export function mintCeoIx({ minter, asset, collection, treasury }) {
  // Order must match the MintCeo accounts struct in the program.
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(minter), isSigner: true, isWritable: true },
      { pubkey: configPda(), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(collection), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(asset), isSigner: true, isWritable: true },
      { pubkey: new PublicKey(treasury), isSigner: false, isWritable: true },
      { pubkey: SLOT_HASHES_SYSVAR, isSigner: false, isWritable: false },
      { pubkey: MPL_CORE_PROGRAM_ID, isSigner: false, isWritable: false },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data: Buffer.from(DISC.mintCeo),
  });
}

/// Decode the fixed head of a Core `AssetV1` account.
///
/// Layout: u8 key (1 = AssetV1), pubkey owner, UpdateAuthority enum
/// (0 None | 1 Address+32 | 2 Collection+32), borsh string name, borsh string
/// uri. Anything past the uri is the plugin registry, which we do not need —
/// the class is recoverable from the name prefix.
export function decodeCoreAsset(address, data) {
  if (data[0] !== 1) return null;
  let o = 1;
  const owner = new PublicKey(data.subarray(o, o + 32)); o += 32;
  const authorityKind = data[o]; o += 1;
  let updateAuthority = null;
  if (authorityKind === 1 || authorityKind === 2) {
    updateAuthority = new PublicKey(data.subarray(o, o + 32)); o += 32;
  }
  const readString = () => {
    const len = Buffer.from(data.subarray(o, o + 4)).readUInt32LE(); o += 4;
    const s = Buffer.from(data.subarray(o, o + len)).toString('utf8'); o += len;
    return s;
  };
  const name = readString();
  const uri = readString();
  const klass = CLASSES.find((c) => name.startsWith(c.name)) ?? null;
  return {
    address: new PublicKey(address),
    owner,
    updateAuthority,
    inCollection: authorityKind === 2,
    name,
    uri,
    class: klass,
    serial: serialOf(name),
    vault: vaultPda(address),
  };
}

/// The number an NFT was minted as, parsed off "<Surname> #<n>". Counters are
/// per class, so this is mint order within a class.
export function serialOf(name) {
  const match = /#(\d+)\s*$/.exec(name ?? '');
  return match ? Number(match[1]) : 0;
}

/// All CEOs in our collection owned by `owner`.
export async function fetchCeosByOwner(connection, owner, collection) {
  const accounts = await connection.getProgramAccounts(MPL_CORE_PROGRAM_ID, {
    filters: [
      { memcmp: { offset: 0, bytes: '2' } }, // base58 of [1] = Key::AssetV1
      { memcmp: { offset: 1, bytes: new PublicKey(owner).toBase58() } },
    ],
  });
  return accounts
    .map(({ pubkey, account }) => decodeCoreAsset(pubkey, account.data))
    .filter((a) => a && a.inCollection && a.updateAuthority.equals(new PublicKey(collection)))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/// Every CEO in the collection, whoever holds it. Filtered server-side on the
/// key byte, the UpdateAuthority variant and the collection pubkey, which all
/// sit at fixed offsets in a Core asset.
export async function fetchCollectionCeos(connection, collection) {
  const accounts = await connection.getProgramAccounts(MPL_CORE_PROGRAM_ID, {
    filters: [
      { memcmp: { offset: 0, bytes: '2' } },
      { memcmp: { offset: 33, bytes: '3' } }, // base58 of [2] = UpdateAuthority::Collection
      { memcmp: { offset: 34, bytes: new PublicKey(collection).toBase58() } },
    ],
  });
  return accounts
    .map(({ pubkey, account }) => decodeCoreAsset(pubkey, account.data))
    .filter(Boolean);
}

// ------------------------------------------------------------- drop engine

export const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
/// Token-2022. Every mainnet xStock is issued under it. The associated-token
/// address is derived from the program id, so a builder that assumes classic
/// SPL Token points at an account that does not exist. Every builder below
/// takes the program explicitly and callers read it from the deploy manifest.
export const TOKEN_2022_PROGRAM_ID = new PublicKey('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb');
export const ASSOCIATED_TOKEN_PROGRAM_ID = new PublicKey('ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL');

/// Fixed-point scale for the per-NFT accumulator. Must match the program.
export const ACC_SCALE = 10n ** 12n;

/// ATAs here are always for PDA owners (the engine, and each vault), so the
/// off-curve path is the normal case rather than the exception.
export function ataFor(mint, owner, tokenProgram = TOKEN_PROGRAM_ID) {
  return PublicKey.findProgramAddressSync(
    [new PublicKey(owner).toBuffer(), new PublicKey(tokenProgram).toBuffer(), new PublicKey(mint).toBuffer()],
    ASSOCIATED_TOKEN_PROGRAM_ID,
  )[0];
}

export function initEngineIx({ authority, stocks, minInterval, dustFloor }) {
  if (stocks.length !== CLASS_COUNT) throw new Error(`stocks must hold exactly ${CLASS_COUNT} mints`);
  const data = Buffer.concat([
    Buffer.from(DISC.initEngine),
    ...stocks.map((m) => new PublicKey(m).toBuffer()),
    i64(minInterval),
    u64(dustFloor),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: true },
      { pubkey: enginePda(), isSigner: false, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data,
  });
}

export function setEngineIx({ authority, minInterval, dustFloor }) {
  const data = Buffer.concat([
    Buffer.from(DISC.setEngine),
    option(minInterval, i64),
    option(dustFloor, u64),
  ]);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: authority, isSigner: true, isWritable: false },
      { pubkey: enginePda(), isSigner: false, isWritable: true },
    ],
    data,
  });
}

export function registerCeoIx({ payer, asset }) {
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(payer), isSigner: true, isWritable: true },
      { pubkey: configPda(), isSigner: false, isWritable: false },
      { pubkey: enginePda(), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(asset), isSigner: false, isWritable: false },
      { pubkey: ceoPda(asset), isSigner: false, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data: Buffer.from(DISC.registerCeo),
  });
}

/// One round for one class. `stockMint` must be that class's mint.
export function runRoundIx({ cranker, classId, stockMint, tokenProgram = TOKEN_PROGRAM_ID }) {
  const engine = enginePda();
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(cranker), isSigner: true, isWritable: false },
      { pubkey: engine, isSigner: false, isWritable: true },
      { pubkey: new PublicKey(stockMint), isSigner: false, isWritable: false },
      { pubkey: ataFor(stockMint, engine, tokenProgram), isSigner: false, isWritable: false },
      // Last, matching the RunRound struct. The program needs it to derive the
      // associated-token address the same way this client just did.
      { pubkey: new PublicKey(tokenProgram), isSigner: false, isWritable: false },
    ],
    data: Buffer.concat([Buffer.from(DISC.runRound), u8(classId)]),
  });
}

export function settleIx({ cranker, asset, stockMint, tokenProgram = TOKEN_PROGRAM_ID }) {
  const engine = enginePda();
  const vault = vaultPda(asset);
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(cranker), isSigner: true, isWritable: true },
      { pubkey: engine, isSigner: false, isWritable: true },
      { pubkey: ceoPda(asset), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(stockMint), isSigner: false, isWritable: false },
      { pubkey: ataFor(stockMint, engine, tokenProgram), isSigner: false, isWritable: true },
      { pubkey: vault, isSigner: false, isWritable: false },
      { pubkey: ataFor(stockMint, vault, tokenProgram), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(tokenProgram), isSigner: false, isWritable: false },
    ],
    data: Buffer.from(DISC.settle),
  });
}

export function closeCeoIx({ authority, asset }) {
  return new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(authority), isSigner: true, isWritable: true },
      { pubkey: enginePda(), isSigner: false, isWritable: true },
      { pubkey: ceoPda(asset), isSigner: false, isWritable: true },
    ],
    data: Buffer.from(DISC.closeCeo),
  });
}

/// Layout: authority, 7x pubkey stocks, 7x u128 acc, 7x u64 outstanding,
/// 7x u32 class_count, 7x i64 last_round, i64 min_interval, u64 dust_floor, u8.
export function decodeEngine(data) {
  const r = readerFor(data);
  const authority = r.pubkey();
  const stocks = times(CLASS_COUNT, r.pubkey);
  const accPerNft = times(CLASS_COUNT, r.u128);
  const outstanding = times(CLASS_COUNT, r.u64);
  const classCount = times(CLASS_COUNT, r.u32);
  const lastRound = times(CLASS_COUNT, r.i64);
  const minInterval = r.i64();
  const dustFloor = r.u64();
  const bump = r.u8();
  return { authority, stocks, accPerNft, outstanding, classCount, lastRound, minInterval, dustFloor, bump };
}

/// Layout: asset, u8 class, u128 stamp, u8 bump.
export function decodeCeo(data) {
  const r = readerFor(data);
  const asset = r.pubkey();
  const classId = r.u8();
  const stamp = r.u128();
  const bump = r.u8();
  return { asset, classId, stamp, bump };
}

/// What one NFT is owed of its class's stock, undelivered — the same arithmetic
/// the program runs in `settle`, so the UI can show it without a crank.
export function owedFor(engine, ceo) {
  const acc = engine.accPerNft[ceo.classId];
  const delta = acc > ceo.stamp ? acc - ceo.stamp : 0n;
  return delta / ACC_SCALE;
}

/// Every registered CEO. One PDA per NFT, so a single program scan finds them.
export async function fetchAllCeos(connection) {
  const accounts = await connection.getProgramAccounts(PROGRAM_ID, {
    filters: [{ memcmp: { offset: 0, bytes: CEO_ACCOUNT_FILTER } }],
  });
  return accounts.map(({ pubkey, account }) => ({ pda: pubkey, ...decodeCeo(account.data) }));
}

/// Ceo PDAs for many assets in one call.
export async function fetchCeoStates(connection, assets) {
  if (!assets.length) return new Map();
  const accounts = await connection.getMultipleAccountsInfo(assets.map(ceoPda));
  return new Map(assets.map((asset, i) => [
    new PublicKey(asset).toBase58(),
    accounts[i] ? decodeCeo(accounts[i].data) : null,
  ]));
}

/// Each vault's balance of ITS OWN class's stock, in as few RPC calls as
/// possible. An NFT only ever holds one stock, so this is one ATA per vault —
/// not a grid. Token account layout: mint(32) owner(32) amount(u64 LE @64).
export async function fetchVaultBalances(connection, holders, engine, tokenProgram = TOKEN_PROGRAM_ID) {
  // holders: [{ asset, classId }]
  if (!holders.length) return new Map();
  const atas = holders.map((h) => ataFor(engine.stocks[h.classId], vaultPda(h.asset), tokenProgram));
  const out = new Map();
  for (let i = 0; i < atas.length; i += 100) {
    const slice = await connection.getMultipleAccountsInfo(atas.slice(i, i + 100));
    slice.forEach((account, j) => {
      const h = holders[i + j];
      const raw = account ? Buffer.from(account.data.subarray(64, 72)).readBigUInt64LE() : 0n;
      // Base units as a decimal string — a BigInt in React state breaks
      // serialisation, and a float cannot sweep 100% exactly.
      out.set(new PublicKey(h.asset).toBase58(), raw.toString());
    });
  }
  return out;
}

// ------------------------------------------------------------------- sweep
//
// Pulling tokens out of a vault needs no program of ours. Core's `ExecuteV1`
// lets the *current owner* of an asset make that asset's signer PDA sign one
// arbitrary instruction, and the signer PDA is the vault. So a sweep is a
// plain SPL transfer whose authority happens to be the vault, wrapped in
// Execute and authorised by the NFT. The right to spend it IS ownership of the
// NFT, checked by Core, and it moves to the buyer the instant the NFT sells.

const CORE_EXECUTE_DISCRIMINATOR = 31;
const TOKEN_TRANSFER_CHECKED = 12;

export function transferCheckedIx({ source, mint, destination, authority, amount, decimals, tokenProgram = TOKEN_PROGRAM_ID }) {
  const data = Buffer.alloc(10);
  data.writeUInt8(TOKEN_TRANSFER_CHECKED, 0);
  data.writeBigUInt64LE(BigInt(amount), 1);
  data.writeUInt8(decimals, 9);
  return new TransactionInstruction({
    programId: new PublicKey(tokenProgram),
    keys: [
      { pubkey: new PublicKey(source), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(mint), isSigner: false, isWritable: false },
      { pubkey: new PublicKey(destination), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(authority), isSigner: false, isWritable: false },
    ],
    data,
  });
}

/// Wrap one instruction so the asset's vault signs it. The vault is marked
/// non-signer in BOTH places it appears — no signature for it exists; Core sets
/// the flag itself via invoke_signed. Marking it a signer here would make the
/// wallet ask for a signature nobody can produce.
export function coreExecuteIx({ asset, collection, owner, payer, inner }) {
  const length = Buffer.alloc(4);
  length.writeUInt32LE(inner.data.length);
  return new TransactionInstruction({
    programId: MPL_CORE_PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(asset), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(collection), isSigner: false, isWritable: true },
      { pubkey: vaultPda(asset), isSigner: false, isWritable: false },
      { pubkey: new PublicKey(payer ?? owner), isSigner: true, isWritable: true },
      { pubkey: new PublicKey(owner), isSigner: true, isWritable: false },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
      { pubkey: new PublicKey(inner.programId), isSigner: false, isWritable: false },
      ...inner.keys.map((k) => ({ ...k, isSigner: false })),
    ],
    data: Buffer.concat([Buffer.from([CORE_EXECUTE_DISCRIMINATOR]), length, inner.data]),
  });
}

/// Move `amount` raw units of a stock from an NFT's vault to its owner.
export function sweepIx({ asset, collection, owner, mint, amount, decimals, tokenProgram = TOKEN_PROGRAM_ID }) {
  const vault = vaultPda(asset);
  return coreExecuteIx({
    asset, collection, owner,
    inner: transferCheckedIx({
      source: ataFor(mint, vault, tokenProgram),
      mint,
      destination: ataFor(mint, owner, tokenProgram),
      authority: vault,
      amount, decimals, tokenProgram,
    }),
  });
}

/// Associated-token-account `CreateIdempotent`. Hand-encoded rather than
/// imported from @solana/spl-token, which touches `Buffer` during module
/// evaluation — before any polyfill in main.jsx can run.
export function createAtaIdempotentIx({ payer, owner, mint, tokenProgram = TOKEN_PROGRAM_ID }) {
  return new TransactionInstruction({
    programId: ASSOCIATED_TOKEN_PROGRAM_ID,
    keys: [
      { pubkey: new PublicKey(payer), isSigner: true, isWritable: true },
      { pubkey: ataFor(mint, owner, tokenProgram), isSigner: false, isWritable: true },
      { pubkey: new PublicKey(owner), isSigner: false, isWritable: false },
      { pubkey: new PublicKey(mint), isSigner: false, isWritable: false },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
      { pubkey: new PublicKey(tokenProgram), isSigner: false, isWritable: false },
    ],
    data: Buffer.from([1]),
  });
}
